@startuml

class User{
  - userId: int
  - username: string
  - password: string
  + email: string
}

abstract class Listing{
  - listingId: int
  + title: string
  + description: string
  + price: double
}

class PropertyListing{
+ area: double
+ rooms: int
}

class VehicleListing{
  + manufacturer: string
  + model: string
  + year: int
  + mileage: int
  + horsepower: int
}

class ProductListing{

}

Listing <|--PropertyListing
Listing <|--ProductListing
Listing <|--VehicleListing


class Category

class UserManager
class SearchManager
class ListingManager
class DatabaseManager

@enduml
